# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distrl/grpc/tensor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64istrl/grpc/tensor.proto\x12\x0e\x64istributed_rl\"m\n\x0bTensorShape\x12-\n\x04\x64ims\x18\x01 \x03(\x0b\x32\x1f.distributed_rl.TensorShape.Dim\x1a/\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x12\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"\xf2\x01\n\x06Tensor\x12\'\n\x05\x64type\x18\x01 \x01(\x0e\x32\x18.distributed_rl.DataType\x12*\n\x05shape\x18\x02 \x01(\x0b\x32\x1b.distributed_rl.TensorShape\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x16\n\nfloat_data\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x17\n\x0b\x64ouble_data\x18\x06 \x03(\x01\x42\x02\x10\x01\x12\x16\n\nint64_data\x18\x07 \x03(\x03\x42\x02\x10\x01\x12\x14\n\x08int_data\x18\x08 \x03(\x05\x42\x02\x10\x01\x12\x15\n\tbool_data\x18\t \x03(\x08\x42\x02\x10\x01*{\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\r\n\tDT_DOUBLE\x10\x02\x12\x0c\n\x08\x44T_INT64\x10\x03\x12\x0c\n\x08\x44T_INT32\x10\x04\x12\x0c\n\x08\x44T_INT16\x10\x05\x12\x0b\n\x07\x44T_INT8\x10\x06\x12\x0b\n\x07\x44T_BOOL\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distrl.grpc.tensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TENSOR'].fields_by_name['float_data']._options = None
  _globals['_TENSOR'].fields_by_name['float_data']._serialized_options = b'\020\001'
  _globals['_TENSOR'].fields_by_name['double_data']._options = None
  _globals['_TENSOR'].fields_by_name['double_data']._serialized_options = b'\020\001'
  _globals['_TENSOR'].fields_by_name['int64_data']._options = None
  _globals['_TENSOR'].fields_by_name['int64_data']._serialized_options = b'\020\001'
  _globals['_TENSOR'].fields_by_name['int_data']._options = None
  _globals['_TENSOR'].fields_by_name['int_data']._serialized_options = b'\020\001'
  _globals['_TENSOR'].fields_by_name['bool_data']._options = None
  _globals['_TENSOR'].fields_by_name['bool_data']._serialized_options = b'\020\001'
  _globals['_DATATYPE']._serialized_start=400
  _globals['_DATATYPE']._serialized_end=523
  _globals['_TENSORSHAPE']._serialized_start=44
  _globals['_TENSORSHAPE']._serialized_end=153
  _globals['_TENSORSHAPE_DIM']._serialized_start=106
  _globals['_TENSORSHAPE_DIM']._serialized_end=153
  _globals['_TENSOR']._serialized_start=156
  _globals['_TENSOR']._serialized_end=398
# @@protoc_insertion_point(module_scope)
